CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
       
CREATE USER flyway WITH PASSWORD 'flyway_ps' NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN;
CREATE USER ai-learning WITH PASSWORD 'ailearning@123' NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN;

GRANT CONNECT ON DATABASE ailearning TO flyway;
GRANT CREATE ON DATABASE ailearning TO flyway;

GRANT CONNECT ON DATABASE ailearning TO ai-learning;

ALTER DEFAULT PRIVILEGES FOR USER flyway IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ai-learning;

ALTER DEFAULT PRIVILEGES FOR USER flyway IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ai-learning;

GRANT ALL ON SCHEMA public TO flyway;
ALTER SCHEMA public OWNER TO flyway;